### ISSUE TITLE
No stack selector dropdown showing

### ISSUE THREAD

**Issue by bjornharink** [andreabassi78/napari-sim-processor#15]
No stack selector dropdown showing. Tried pip install on Python 3.10.9:

![image](https://user-images.githubusercontent.com/13664890/206748458-45c7be84-b624-4999-8c8e-109d6c970c99.png)

```
KeyError                                  Traceback (most recent call last)
File C:\Frameworks\Python310\lib\site-packages\napari_sim_processor\_sim_widget.py:759, in SimAnalysis.calculate_WF_image(self=<napari_sim_processor._sim_widget.SimAnalysis object>)
    753 def calculate_WF_image(self):
    754     '''
    755     Calculates and shows the widefield image from the raw 5D image stack.
    756     It averages the data on all phases and angles.
    757     Shows the resulting 3D image stack as an Image layer of the viewer.
    758     '''
--> 759     imageWFdata = np.mean(self.get_hyperstack(), axis=(0,1))
        np = <module 'numpy' from 'C:\\Frameworks\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
        self = <napari_sim_processor._sim_widget.SimAnalysis object at 0x0000015C44542320>
    760     imname = 'WF_' + self.imageRaw_name
    761     scale = self.viewer.layers[self.imageRaw_name].scale

File C:\Frameworks\Python310\lib\site-packages\napari_sim_processor\_sim_widget.py:436, in SimAnalysis.get_hyperstack(self=<napari_sim_processor._sim_widget.SimAnalysis object>)
    434     return self.viewer.layers[self.imageRaw_name].data
    435 except:
--> 436     raise(KeyError('Please select a valid stack'))

KeyError: 'Please select a valid stack'
```

Then tried standalone install:

```
File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app\napari\__main__.py", line 565, in <module>
    sys.exit(main())
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app\napari\__main__.py", line 327, in _run
    viewer = Viewer()
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app\napari\viewer.py", line 65, in __init__
    _initialize_plugins()
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app\napari\plugins\__init__.py", line 46, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "C:\Users\bjorn\AppData\Local\Programs\napari\\app_packages\npe2\manifest\schema.py", line 228, in from_distribution
    raise ValueError(
ValueError: Distribution {name!r} exists but does not provide a napari manifest
```

**Comment by bjornharink** [comment]
Changing `magicgui` to version 0.5.1 fixes it indeed (`pip install magicgui=0.5.1`). The selection is now available. Unfortunately, as you predicted there are many other error popping up. I'll try a Python 3.9 instead. 

Thank you for checking into this. Much appreciated.

**Comment by pptman** [comment]
I have added a branch `fixesforpython3.10` that I think has sorted the problems that come from using later versions of numpy, pytorch and napari.  The magicgui issue is still there so needs work still.  

This works on my 3.10 install with numpy(1.24.1) pytorch(2.0.0) and napari(0.4.17) packages and on python 3.9 with earlier versions of those packages.

**Comment by andreabassi78** [comment]
Hi @bjornharink, sorry for taking it so long to respond. We fixed the issue, along with others, and the dropdown menu works now, as tested in python 3.8, 3.10 (windows, mac). The new version of the plugin on NapariHub, v0.0.10, contains these changes.
